<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	
	<!-- jQuery -->
	<script type="text/javascript" src="/js/jquery-1.11.2.min.js"></script>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="/css/bootstrap.min.css">
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>

	<!-- Styles -->
	<link rel="stylesheet" href="/css/style.css">

	<!-- Javascript -->
	<script type="text/javascript" src="/js/main.js"></script>

	<!-- HTML5 Shiv -->
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>